remove error handler, and comment out specs
caplinked/caplinked-api-ruby pull request #5
Opened 2016-12-15 01:32 UTC by garcha

2016-12-20 17:51 UTC, jordanfowler commented
CR'ed 👍

2016-12-28 22:18 UTC, aronslee requested changes

2016-12-28 22:18 UTC, aronslee commented on Gemfile.lock
> +BUNDLED WITH
remove 133 and 134

2016-12-28 22:18 UTC, aronslee commented on spec/core/client_spec.rb
> +    client = Caplinked::Client.new api_key: ENV["API_KEY"], api_host: 'secure.caplinked.com', api_scheme: 'https'
Just use some dummy string for api_key instead of ENV var

2016-12-28 22:18 UTC, aronslee commented on spec/core/client_spec.rb
> +    expect(client.api_key).to eq(ENV["API_KEY"])
Just use some dummy string for api_key instead of ENV var

2016-12-28 22:18 UTC, aronslee commented on spec/core/client_spec.rb
> +    expect(client.api_scheme).to eq("https")
should only accept https or http and default to https in client

2016-12-28 22:18 UTC, aronslee commented on spec/core/request.rb
> +    expect(request.client.api_host).to eq("sandbox.caplinked.com")
would be good to also test result of @uri

2016-12-28 22:18 UTC, aronslee commented on spec/core/request.rb
> +    stub_request(:get, "https://sandbox.caplinked.com/api/v1/files/38187?workspace_id=5886").
you dont need this stub here right bc you are not calling perform on the http request?

2016-12-28 22:19 UTC, aronslee commented
@garcha also test & fixture json response for a couple error examples would nice

2016-12-28 23:00 UTC, garcha commented on spec/core/client_spec.rb
> +    expect(client.api_scheme).to eq("https")
default is https, but any value can be passed in. I think its fine, the users that will have access are paying customers anyways.

2016-12-28 23:00 UTC, garcha commented on spec/core/client_spec.rb
> +    client = Caplinked::Client.new api_key: ENV["API_KEY"], api_host: 'secure.caplinked.com', api_scheme: 'https'
done

2016-12-28 23:00 UTC, garcha commented on spec/core/client_spec.rb
> +    expect(client.api_key).to eq(ENV["API_KEY"])
done

2016-12-28 23:09 UTC, garcha commented on spec/core/request.rb
> +    stub_request(:get, "https://sandbox.caplinked.com/api/v1/files/38187?workspace_id=5886").
done

2016-12-28 23:09 UTC, garcha commented on spec/core/request.rb
> +    expect(request.client.api_host).to eq("sandbox.caplinked.com")
done

2016-12-29 19:27 UTC, aronslee approved these changes

2016-12-29 23:55 UTC, garcha commented
Ready to merge.

2016-12-29 23:55 UTC, merged